spring:
  application:
    name: UserService


  datasource:
    username:
    password:
    url: jdbc:postgresql://localhost:5555/test_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
