spring:
  application:
    name: GatewayService

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
          filters:
            - TokenValidationFilter

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - TokenValidationFilter

        - id: security-service
          uri: http://localhost:8083
          predicates:
            - Path=/security/**
          filters:
            - TokenValidationFilter

Jwt:
  secret: mySuperSecretKeyWithAtLeast64BytesLength123Ph67890123456kow0123456789012
